# GitHub Workflow for Auto-updating Scoop Bucket
#
# Author: Dragon1573
###############################################################################

name: Refresh Bucket
on:
  schedule:
    # A scheduled workflow toggled every 3 hours starting from 00:00 every day.
    - cron: "0 */3 * * *"

defaults:
  run:
    shell: pwsh

jobs:
  update:
    runs-on: windows-latest
    steps:
      - name: Install Scoop
        run: |
          # Enable Powershell Authority
          Set-ExecutionPolicy RemoteSigned -scope CurrentUser
          # Install Scoop
          Invoke-Expression (New-Object System.Net.WebClient).DownloadString('https://get.scoop.sh')
      - name: Checkout
        uses: actions/checkout@v2.3.4
      - name: Config Myself
        run: |
          git config --local user.email "Legend_1949@126.com"
          git config --local user.name "Dragon1573"
      - name: Version Check
        run: python utils/autoUpdate.py
      - name: Push Updates
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: main
