# GitHub Workflow for Auto-updating Scoop Bucket
#
# Author: Dragon1573
###############################################################################

name: Refresh Bucket
on:
  push:
  schedule:
    # Cron Syntax:
    #   - minutes (0 - 59)
    #   - hours (0 - 23)
    #   - day of month (1 - 31)
    #   - month of year (1 - 12)
    #   - day of week (0 - 6)
    - cron: "0 0/6 * * *"

env:
  SCOOP: C:\Scoop\
  SCOOP_GLOBAL: C:\Scoop\global

defaults:
  run:
    shell: pwsh -File {0}

jobs:
  update:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Cache Scoop
        id: cache
        uses: actions/cache@v2
        with:
          path: C:\Scoop
          key: scoop-cache
      - name: Install Scoop
        if: steps.cache.outputs.cache-hit != 'true'
        run: |
          Set-ExecutionPolicy RemoteSigned -scope CurrentUser
          Invoke-Expression (New-Object System.Net.WebClient).DownloadString('https://get.scoop.sh')
      - name: Version Check
        run: |
          $env:PATH += ';C:\Scoop\shims'
          .\bin\checkver.ps1 -U *
          .\bin\checkver.ps1 -U * *> ..\update.log
      - name: Format commit log
        shell: bash
        run: |
          sed -i 'N;s/\n//g' ../update.log
          sed -i 's/^/- /g' ../update.log
          sed -i '1i Actions[bot]: Update Apps\n' ../update.log
      - name: Read commit log
        id: changelog
        uses: juliangruber/read-file-action@v1
        with:
          path: ../update.log
      - name: Add & Commit
        uses: EndBug/add-and-commit@v7
        with:
          add: "bucket"
          branch: main
          default_author: github_actions
          message: ${{ steps.changelog.outputs.content }}
          push: true
