# GitHub Workflow for Auto-updating Scoop Bucket
#
# Author: Dragon1573
###############################################################################

name: Scoop CI
on:
  schedule:
    # Cron Syntax:
    #   - minutes (0 - 59)
    #   - hours (0 - 23)
    #   - day of month (1 - 31)
    #   - month of year (1 - 12)
    #   - day of week (0 - 6)
    - cron: "0 0/6 * * *"
jobs:
  update:
    name: Excavate
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Excavate
        uses: shovel-org/GithubActions@main
        env:
          GITH_EMAIL: actions@github.com
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SKIP_UPDATED: '1'
          SHOVEL: '1'
          SCOOP_BRANCH: NEW
