# GitHub Workflow for Auto-updating Scoop Bucket
#
# Author: Dragon1573
###############################################################################

name: Refresh Bucket
on:
  push:
  schedule:
    # Cron Syntax:
    #   - minutes (0 - 59)
    #   - hours (0 - 23)
    #   - day of month (1 - 31)
    #   - month of year (1 - 12)
    #   - day of week (0 - 6)
    - cron: "0 0/6 * * *"

defaults:
  run:
    shell: pwsh

jobs:
  update:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4
      - name: Version Check
        # Each runs are in different shell. They are isolated so Python could
        # not detect the installation of scoop. Put them together to avoid
        # this exception.
        run: |
          # Enable Powershell Authority
          Set-ExecutionPolicy RemoteSigned -scope CurrentUser
          # Install Scoop
          Invoke-Expression (New-Object System.Net.WebClient).DownloadString('https://get.scoop.sh')
          # Version Check by Scoop
          python utils/autoUpdate.py
      - name: Push Updates
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: main
