# GitHub Workflow for Auto-updating Scoop Bucket
#
# Author: Dragon1573
###############################################################################

name: Refresh Bucket
on:
  push:
  schedule:
    # Cron Syntax:
    #   - minutes (0 - 59)
    #   - hours (0 - 23)
    #   - day of month (1 - 31)
    #   - month of year (1 - 12)
    #   - day of week (0 - 6)
    - cron: "0 0/6 * * *"

env:
  SCOOP: C:\Scoop\
  SCOOP_GLOBAL: C:\Scoop\global

defaults:
  run:
    shell: pwsh -File {0}

jobs:
  update:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Cache Scoop
        id: cache
        uses: actions/cache@v2
        with:
          path: C:\Scoop
          key: scoop-cache
      - name: Install Scoop
        if: steps.cache.outputs.cache-hit != 'true'
        run: |
          Set-ExecutionPolicy RemoteSigned -scope CurrentUser
          Invoke-Expression (New-Object System.Net.WebClient).DownloadString('https://get.scoop.sh')
      - name: Version Check
        run: |
          $env:PATH += ';C:\Scoop\shims'
          .\bin\checkver.ps1 -U *
          .\bin\checkver.ps1 -U * *> update.log
      - name: Create commit
        shell: bash
        run: |
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          sed -i 'N;s/\n//g' update.log     # Generate update log from shell
          sed -i 's/^/- /g' update.log      # Format update log
          sed -i '1i Actions[bot]: Update Apps\n' update.log    # Append Subject line
          git add bucket/
          if [ -z "$(git status --porcelain)" ]; then
              echo 'Everything up to date!'
          else
              git commit -F update.log
          fi
      - name: Push Updates
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: main
